### ISSUE TITLE
Prevent accidental closing when upload is in progress

### ISSUE THREAD

**Issue by Makkes** [Makkes/fileboy-node#19]
As a user, I want the browser to warn me when I am about to close a tab where a Fileboy upload is in progress.

**Comment by Makkes** [comment]
@dx17: for you. ;)

**Comment by dx17** [comment]
Thank you so much :-D

**Comment by Makkes** [comment]
Fixed and deployed

**Comment by dx17** [comment]
YEAH :+1:
